server:
  port: 8888

upload:
  path: /images/2/
  base-url: http://dev.macacolabs.site
  port: 21
  userId: team2
  password: 1234qwer

spring:
  application:
    name: fundyserver

  config:
    import: classpath:secret.yml


  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        naming:
          physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    database-platform: org.hibernate.dialect.MySQL8Dialect

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100

logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.springframework.web: DEBUG
    io.fundy.fundyserver: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.thymeleaf: TRACE

  web:
    resources:
      add-mappings: false

frontend:
  url: http://localhost:3000